### ISSUE TITLE
add filtered `exodus:` to result

### ISSUE THREAD

**Issue by rkoster** [genesis-community/testkit#6]
Filter out:
```
exodus:      
  version: 
  dated:
  deployer:
  kit_name:
  kit_version:
  vault_base:
```
